# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestNativeNavigation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestNativeNavigation

  target 'TestNativeNavigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestNativeNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestNativeNavigation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestNativeNavigation-tvOS

  target 'TestNativeNavigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
