# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestNativeNavigation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'native-navigation', :path => '../node_modules/native-navigation'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork'
    # Add any other subspecs you want to use in your project
  ]

  # Pods for TestNativeNavigation
  target 'TestNativeNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
